// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class Colunas
{
    public int Coluna { get; set; }

    public int Numero { get; set; }

    public virtual Numeros NumeroNavigation { get; set; }
}