// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class Configuration
{
    public int ConfigurationId { get; set; }

    public string ConfigurationKey { get; set; }

    public string ConfigurationValue { get; set; }
}