// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class EstatisticasNumerosUltimaDatum
{
    public string Tabela { get; set; }

    public DateTime Data { get; set; }
}