// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class EstatisticasParImpar
{
    public int EstatisticasParImparId { get; set; }

    public string ParImpar { get; set; }

    public int Quantidade { get; set; }
}