// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class Jogo
{
    public int IdJogo { get; set; }

    public int NumeroJogo { get; set; }

    public DateTime Data { get; set; }

    public int Numero1 { get; set; }

    public int Numero2 { get; set; }

    public int Numero3 { get; set; }

    public int Numero4 { get; set; }

    public int Numero5 { get; set; }

    public int NumeroSorte { get; set; }

    public virtual NumerosDoSorteio Numero1Navigation { get; set; }

    public virtual NumerosDoSorteio Numero2Navigation { get; set; }

    public virtual NumerosDoSorteio Numero3Navigation { get; set; }

    public virtual NumerosDoSorteio Numero4Navigation { get; set; }

    public virtual NumerosDoSorteio Numero5Navigation { get; set; }

    public virtual NumerosDaSorte NumeroSorteNavigation { get; set; }
}