// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class Jogos
{
    public int IdJogo { get; set; }

    public int Jogo { get; set; }

    public DateTime Data { get; set; }

    public int Numero1 { get; set; }

    public int Numero2 { get; set; }

    public int Numero3 { get; set; }

    public int Numero4 { get; set; }

    public int Numero5 { get; set; }

    public int NumeroSorte { get; set; }
}