// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class NumerosDoSorteio
{
    public int Numero { get; set; }

    public bool Par { get; set; }

    public bool Impar { get; set; }

    public bool Borda { get; set; }

    public bool Miolo { get; set; }

    public bool DiagonalDireita { get; set; }

    public bool DiagonalEsquerda { get; set; }

    public int Linha { get; set; }

    public int Coluna { get; set; }

    public virtual Coluna ColunaNavigation { get; set; }

    public virtual EstatisticasNumerosDoSorteio EstatisticasNumerosDoSorteio { get; set; }

    public virtual ICollection<Jogo> JogoNumero1Navigations { get; set; } = new List<Jogo>();

    public virtual ICollection<Jogo> JogoNumero2Navigations { get; set; } = new List<Jogo>();

    public virtual ICollection<Jogo> JogoNumero3Navigations { get; set; } = new List<Jogo>();

    public virtual ICollection<Jogo> JogoNumero4Navigations { get; set; } = new List<Jogo>();

    public virtual ICollection<Jogo> JogoNumero5Navigations { get; set; } = new List<Jogo>();

    public virtual Linha LinhaNavigation { get; set; }

    public virtual ICollection<SequenciaNumerosDoSorteio> SequenciaNumerosDoSorteioNumeroMesmoJogoNavigations { get; set; } = new List<SequenciaNumerosDoSorteio>();

    public virtual ICollection<SequenciaNumerosDoSorteio> SequenciaNumerosDoSorteioNumeroNavigations { get; set; } = new List<SequenciaNumerosDoSorteio>();

    public virtual ICollection<SequenciaNumerosDoSorteioSorte> SequenciaNumerosDoSorteioSortes { get; set; } = new List<SequenciaNumerosDoSorteioSorte>();
}