// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class Numeros
{
    public int Numero { get; set; }

    public bool Par { get; set; }

    public bool Impar { get; set; }

    public bool Borda { get; set; }

    public bool Miolo { get; set; }

    public bool DiagonalDireita { get; set; }

    public bool DiagonalEsquerda { get; set; }

    public virtual ICollection<Colunas> Colunas { get; set; } = new List<Colunas>();

    public virtual ICollection<Jogos> JogosNumero1Navigation { get; set; } = new List<Jogos>();

    public virtual ICollection<Jogos> JogosNumero2Navigation { get; set; } = new List<Jogos>();

    public virtual ICollection<Jogos> JogosNumero3Navigation { get; set; } = new List<Jogos>();

    public virtual ICollection<Jogos> JogosNumero4Navigation { get; set; } = new List<Jogos>();

    public virtual ICollection<Jogos> JogosNumero5Navigation { get; set; } = new List<Jogos>();

    public virtual ICollection<Linhas> Linhas { get; set; } = new List<Linhas>();
}