// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TotolotoRepository.Models;

public partial class NumerosDaSorte
{
    public int Numero { get; set; }

    public bool Par { get; set; }

    public bool Impar { get; set; }

    public virtual EstatisticasNumerosDaSorte EstatisticasNumerosDaSorte { get; set; }

    public virtual ICollection<Jogo> Jogos { get; set; } = new List<Jogo>();
}