// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TotolotoRepository.Models;

public partial class TotolotoContext : DbContext
{
    public TotolotoContext(DbContextOptions<TotolotoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Jogos> Jogos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Jogos>(entity =>
        {
            entity.HasKey(e => e.IdJogo);

            entity.Property(e => e.Data).HasColumnType("datetime");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}